laser_scan_matcher:
  ros__parameters:
    publish_odom: "odom"
    publish_tf: True
    base_frame: "7/base_link"
    odom_frame: "odom"
    map_frame: "map"
    laser_frame: "laser_frame"
    kf_dist_linear: 0.10
    kf_dist_angular: 0.17453292519943295
